### ISSUE TITLE
Críticas constructivas cuatrimestre 2015 2c

### ISSUE THREAD

**Issue by diegosanchez** [untref/clanguage#3]
Por favor, para los alumnos de este cuatrimestre por favor escriban aquí sus críticas constructivas. Por favor solo un comentario por persona.

**Comment by gonzalocozzi** [comment]
1. Es fundamental hacer más práctica. El conocimiento de los temas se refuerza y asienta con ella y creo que debe ser más abundante.
2. Cuando se anuncian ejercicios prácticos envíelos en el transcurso de la semana siguiente, y lo antes posible. No los demore innecesariamente.
3. Si las calificaciones de los recuperatorios van a reemplazar a las calificaciones de los exámenes iniciales aclárelo en el documento de condiciones de aprobación y promoción, ya que es injusto para quien perdió la posibilidad de promocionar por haber obtenido un 4 o 5 en esos exámenes y no saber que podía recuperar y arriesgarse a obtener una mejor calificación. De hecho también es injusto este detalle para considerar las calificaciones de los promocionados, que habiendo hecho recuperatorios pueden quedar encima de quienes no los hicieron.
4.  No suponga que no estudiamos cuando respondemos mal una pregunta en clase, es intimidatorio y no fomenta la participación. Estoy convencido de que las devoluciones a los ejercicios y exámenes pueden ser más diplomáticas, lo que no implica que no sean sinceras o directas.
5. Que las consignas sean claras y eviten la ambigüedad, lo ambiguo esta mal expresado, promueve cometer errores y puede dar motivo a discusiones innecesarias sobre la naturaleza de los ejercicios.
6. Para próximos cuatrimestres yo no haría el trabajo práctico del JSON, porque futuras comisiones podrían copiarse de nuestros trabajos.
7. Sea más explícito con la idea de "buenas prácticas de programación" para el trabajo práctico. Lamentablemente es un error suponer que las materias previas a Lenguajes III son sólidas en este aspecto, y no vendría mal una profundización del asunto.
8. Cuando el trabajo práctico define 4 entregas, que sean 4 entregas (4 semanas de trabajo) y no 3 como fue en nuestra comisión. Esa única semana de trabajo, en un contexto de numerosos exámenes y entregas, puede ser crucial. De hecho yo comenzaría el trabajo antes (posiblemente después del primer parcial) para que no se superponga con los exámenes o que al menos esté claramente definido para esa altura del cuatrimestre.

**Comment by MarcoKlemenc** [comment]
Voy a tomar como base el comentario de Gonzalo y agregar algunas observaciones a cada punto que planteó:
1. Concuerdo. Como dato extra, me pareció que había un salto de dificultad un poco pronunciado entre las prácticas "post-clase" y los ejercicios de repaso. Creo que sería bueno incluirlos todos en una guía de práctica después de cada clase, junto con un par de ejercicios "intermedios".
Además, buscaría evitar dar temas la clase inmediatamente anterior al parcial. Desde mi punto de vista, debería ser una clase de "redondeo" de todos los temas dados anteriormente y de despeje de dudas por parte de los alumnos.
2. Concuerdo. De hecho, en algunas materias de programación los ejercicios estaban subidos antes de la clase. Es un poco extremo, pero si uno quería podía ponerse a programar apenas llegaba de cursar.
3. Quizá tenga una opinión algo subjetiva (promocioné vía recuperatorio), pero se me hace que es un punto bastante más debatible, ya que el criterio para la nota final varía mucho de una materia a otra (por ejemplo, cuando cursé ED II no era promocionable, y la nota del analítico fue un promedio entre la de los parciales, el TP y el final), agregando también que, por lo general, en las materias de programación, vi que se permita recuperar para tratar de promocionar.
4. Concuerdo con lo primero, con respecto a la consideración de que las devoluciones puedan ser "más diplomáticas", quizá la búsqueda de un poco más de nota (especialmente en una materia promocionable) genere ciertas disidencias con respecto a la corrección (me incluyo).
5. Quizá hable desde una posición subjetiva, pero creo que hubo algunas consignas (en exámenes y TP) que podrían haber sido mejor formuladas (ej. el famoso TDA del primer parcial, o explicitar desde el comienzo que el JSON no debía incluir saltos de línea).
6. No creo que se repita la consigna para las próximas comisiones.
7. Acá disiento un poco, más allá de que en qué nivel se detalle el concepto en materias anteriores, creo que es algo que uno ya debe tener incorporado a partir de la práctica.
8. Concuerdo. Más aún teniendo en cuenta que eran las primeras dos entregas, que podían llegar a sentar las bases para el resto del TP.

**Comment by diegosanchez** [comment]
Gracias a ambos. Respecto a las/los críticas/comentarios:
1. Sí, estamos trabajando en un guía para el próximo ciclo.
2. Esto se soluciona teniendo una guía de ejercicios.
3. Las condiciones de promoción están desde el primer día de clase y creo que son claras. Esto se soluciona **preguntando**, simplemente.
4. Desglozo la respuesta:
   4.1. Respecto a la diplomacia (no recuerdo un episodio que atente contra este principio)
   4.2. Respecto a mis consideraciones acerca del compromiso de los alumnos para con la materia, es potestad mía.
5. Desglozo la respuesta:
   5.1. Creemos haberlo revertido en los recuperatorios y segundo parcial. Seguiremos en este camino.
   5.2. _...o explicitar desde el comienzo que el JSON no debía incluir saltos de línea_: se explicó en clase cuando se entregó el TP.
6. Respecto a la consigna, nos reservamos el derecho de plantear el TP que creemos adecuado.
7. _Buenas prácticas_: 
   7.1. Son conceptos que se vienen impartiendo en materias correlativas.
   7.2. Si el enunciado es ambigüo, siempre existen instancias de consulta, de todos modos el TP Final lista una _Pautas de Calidad_ q se consideran a la hora de corregir el TP.
8. Sí, hubo una serie de feriados que nos perjudicaron.

**Comment by armaldini** [comment]
Comparto las opiniones de mis compañeros en los ítems 1,2, 4, 5 y 8.
Personalmente, creo que estaría bueno tener una guía de ejercicios con las resoluciones disponibles para el alumno desde el primer día. Las soluciones son necesarias para poder despejar dudas en el momento que uno se pone a hacer un ejercicio y no tener que esperar hasta la próxima clase o a que el profesor conteste un mail si le enviamos una consulta por ese medio. 
Más allá de las correcciones a los ejercicios de "tarea", que también son muy útiles, creo que es mejor poder hacer ejercicios en clase y encontrar un equilibrio entre teoría y práctica. Pero práctica no viendo lo que hace el profesor, si no sentándonos a programar en máquina durante la clase para sacarnos la mayor cantidad de dudas teniendo al profesor presente.
La mayoría de los alumnos tiene otras ocupaciones y responsabilidades que cumplir además de la universidad, que insumen tiempo que muchas veces se ve reducido si tenemos que hacer absolutamente toda la práctica fuera de la clase. Ya estamos invirtiendo cuatro horas semanales en ir a cursar, y creo que debería aprovecharse al máximo ese tiempo y no obligar al alumno a que le dedique muchas horas más fura de la universidad a la misma materia. Porque no nos sobra el tiempo como para permitirnos ese lujo.
Además de las resoluciones a las guías de ejercicios, creo que podría mejorar también la calidad de las diapositivas de teoría que se suben al sitio de la materia, puesto que muchas no presentan suficiente información como para poder entenderse por sí mismas. Habiendo faltado a una clase, puedo asegurar que sin la explicación del profesor, no sirven de mucho las diapositivas.
Yo sé que siempre se puede recurrir al profesor y consultarle por distintos medios nuestras dudas, pero es mucho mejor tener disponible esa información de entrada. Sería más sencillo para nosotros que no tenemos que esperar a que nos respondan la consulta y tener que volver a reservarnos tiempo para realizar las prácticas en casa, y para el docente que no tiene que chequear y responder consultas constantemente y quizás aclarar más de una vez la misma duda.
